BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'vertical'
        id: main_box

    Label:
        size_hint_y: 0.1
        text: app.status_text

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        Button:
            text: 'Create Widgets'
            on_release: app.add_widgets()
        Button:
            text: 'Remove All Widgets'
            on_release: app.clear_all()


